config/routes.rb
Rails.application.routes.draw do
  # devise_for :devise_users, :controllers => {registrations: "devise_users/registrations"}

  # devise_for :devise_users, :controllers => {registrations: "devise_users/registrations",
  #                                            sessions: "devise_users/sessions"} do
  #       get "devise_users/sign_up", to: "devise_users/registrations#new"
  # end

  devise_for :devise_users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: "products#index"

  # generate all 7 RESTful routes:

  resources :pages

  resources "products", only: %i[index show]
  resources :shopping_carts
  resources :line_items
  resources :addresses

  get "categories", to: "categories#index"

  get "search", to: "products#search", as: "search" #search_path

  get "/p/:permalink", to: "pages#permalink", as: "permalink"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :province
  belongs_to :devise_user
  validates :street_number, :apartment_number, :city, :postcode, :devise_user_id, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/models/devise_user.rb
class DeviseUser < ApplicationRecord
  # before_action :authenticate_user!
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :addresses
  has_one :shopping_cart
  has_one_attached :image
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :shopping_cart
  validates :quantity, :product_id, :shopping_cart_id, presence: true


end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :devise_user
  has_many :order_products
  validates :o_price, numericality: true
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_products
  has_many :line_items
  validates :name, :price, :is_in_stock, :description, :category_id, presence: true
  validates :price, numericality: true
  has_one_attached :active_image
  validates :discount_rate, presence: false
  paginates_per 9

  before_destroy :ensure_not_referenced_by_any_line_item

  private
  #ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, 'Line Items present')
      throw :abort
    end
  end
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :addresses
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :devise_user

  has_many :line_items, dependent: :destroy

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/controllers/pages_controller.rb
class PagesController < InheritedResources::Base
  http_basic_authenticate_with name: "admin", password: "password", except: :permalink
  before_action :fetch_items_count
  before_action :user_helper


  def permalink
    @page = Page.find_by(permalink: params[:permalink])
    redirect_to root_path if @page.nil?
  end

  private

  def page_params
    params.require(:page).permit(:title, :content, :permalink)
  end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  before_action :set_cart, only: [:index, :show, :create]
  before_action :get_products_array
  before_action :date_card
  before_action :fetch_items_count

  # GET /carts
  # GET /carts.json
  def index
    set_cart
    get_products_array
  end

  def show
    set_cart
    get_products_array
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = ShoppingCart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    if @cart.id == session[:cart_id]
      session[:cart_id] = nil
    end

    respond_to do |format|
      format.html { redirect_to store_index_url, notice: "Your cart is currently empty" }
      format.json { head :no_content }
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def cart_params
    params.fetch(:cart, {})
  end

  def invalid_cart
    logger.error "Attempt to access invalid cart#{params[:id]}"
    redirect_to store_index_url, notice: "Invalid cart"
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/callback_helper.rb
module CallbackHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/views/shopping_carts/_cart.html.erb
<table  class="table table-sm">
  <thead>
    <tr scope="col" class="table-info text-center">
      <th scope="col">Line No.</th>
      <th scope="col">Name</th>
      <th scope="col">Price</th>
      <th scope="col">Quantity</th>
      <th scope="col">Total</th>
      <th scope="col" >Action</th>
    </tr>
    </thead>
    <tbody>
      <p style="display: none;"><%= i = 0 %></p>
      <p style="display: none;"> <%= subtotal = 0 %> </p>
    <% items_array.each do |line_item| %>
      <tr >
        <td class="text-center" scope="row"> <%= i += 1 %></td>
        <td class="text-center" > <%= line_item[0] %> </td>
        <td class="text-center"> <%= number_to_currency line_item[1] %></td>
        <td class="text-center"> <%= line_item[2] %></td>
        <td class="text-center"> <%= number_to_currency (line_item[1] * line_item[2] ) %></td>
        <p style="display: none;"><%= subtotal += (line_item[1] * line_item[2]) %></p>
        <td class="text-center"> <%= link_to "Remove", line_item_path(line_item[3]), method: :delete, data: { confirm: "Are you sure? " }, class: "btn btn-warning", style: "font-size: 0.8em;" %></td>
      </tr>
    <% end %>
    <tr class="table-active">
        <th colspan="4" >Date: <%= @date %></th>
        <th>SubTotal: </th>
        <th><%= number_to_currency subtotal %> </th>
      </tr>
  </tbody>
</table>

app/views/shopping_carts/_form.html.erb
<%= form_with(model: shopping_cart, local: true) do |form| %>
  <% if shopping_cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shopping_cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% shopping_cart.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shopping_carts/_shopping_cart.html.erb
<article>
  <% if notice %>
    <aside id="notice"><%= notice %></aside>
  <% end %>
  <h2>Your Cart</h2>
  <table>

      <%= render shopping_cart.line_items %>

    <tfoot>
      <tr>
        <th colspan="2">Total:</th>
        <td class="price"> <%= number_to_currency(shopping_cart.total_price) %></td>
      </tr>
    </tfoot>
  </table>
  <%= button_to 'Empty cart', shopping_cart, method: :delete, data: {confirm: 'Are you sure?'} %>
</article>

app/views/shopping_carts/index.html.erb
<%= render partial: "cart", locals: { items_array: @items_array } %>

app/views/shopping_carts/show.html.erb
<h2>Your Cart</h2>
<%= render partial: "cart", locals: { items_array: @items_array } %>