config/routes.rb
Rails.application.routes.draw do
  # devise_for :devise_users, :controllers => {registrations: "devise_users/registrations"}

  # devise_for :devise_users, :controllers => {registrations: "devise_users/registrations",
  #                                            sessions: "devise_users/sessions"} do
  #       get "devise_users/sign_up", to: "devise_users/registrations#new"
  # end

  devise_for :devise_users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: "products#index"

  # generate all 7 RESTful routes:

  resources :pages

  resources "products", only: %i[index show]
  resources :shopping_carts
  resources :line_items
  resources :addresses

  get "categories", to: "categories#index"

  get "search", to: "products#search", as: "search" #search_path

  get "/p/:permalink", to: "pages#permalink", as: "permalink"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :province
  belongs_to :devise_user
  validates :street_number, :apartment_number, :city, :postcode, :devise_user_id, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/models/devise_user.rb
class DeviseUser < ApplicationRecord
  # before_action :authenticate_user!
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :addresses
  has_one :shopping_cart
  has_one_attached :image
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :shopping_cart
  validates :quantity, :product_id, :shopping_cart_id, presence: true


end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :devise_user
  has_many :order_products
  validates :o_price, numericality: true
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_products
  has_many :line_items
  validates :name, :price, :is_in_stock, :description, :category_id, presence: true
  validates :price, numericality: true
  has_one_attached :active_image
  validates :discount_rate, presence: false
  paginates_per 9

  before_destroy :ensure_not_referenced_by_any_line_item

  private
  #ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, 'Line Items present')
      throw :abort
    end
  end
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :addresses
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :devise_user

  has_many :line_items, dependent: :destroy

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/controllers/pages_controller.rb
class PagesController < InheritedResources::Base
  http_basic_authenticate_with name: "admin", password: "password", except: :permalink
  before_action :fetch_items_count
  before_action :user_helper


  def permalink
    @page = Page.find_by(permalink: params[:permalink])
    redirect_to root_path if @page.nil?
  end

  private

  def page_params
    params.require(:page).permit(:title, :content, :permalink)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # before_action :set_cart, only: [:search, :show, :create]
  before_action :fetch_items_count
  before_action :user_helper

  def index
    @categories = Category.all.includes(:products)

    cate = params[:cate]
    if !cate.nil?
      @category = Category.find(cate)
      @products = Product.where(category_id: cate).order(:id).page(params[:page])
    else
      @products = Product.order(:id).page(params[:page])
    end
  end

  def show
    set_cart
    @product = Product.find(params[:id])
    @cate = Category.find(@product.category_id)

    if devise_user_signed_in?
      @line_item = LineItem.new do |l|
        l.product_id = @product.id
        l.shopping_cart_id = @cart.id
      end
    end

    # all_i = current_devise_user.shopping_cart.line_items.group(:product_id).sum(:quantity)
    # all_i.each do |k, v|
    #   puts("#####  #{Product.find(k).name}")
    #   puts("#####  #{v.inspect}")
    # end
    # puts("#####  #{all_i.inspect}")
  end

  # GET /search/?search_temr = user + search +terms
  def search
    if params[:category_id].blank?
      @products = Product.where("name LIKE ?", "%#{params[:search_term]}%")
      @cate = nil
    else
      @products = Category.find(params[:category_id]).products.where("name LIKE ?", "%#{params[:search_term]}%")
      @cate = Category.find(params[:category_id])
    end
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/callback_helper.rb
module CallbackHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/views/products/_search_form.html.erb
<%= form_with(url: search_path, local:true, method: "get") do %>
<%= text_field_tag(:search_term, nil, style: "width:150px; height:30px;", class:"option rounded border border-secondary ml-2 mr-2 pl-1", placeholder:"Search", type:"search") %>
<% c_array = Category.all { |c| [c.name, c.id] } %>
<%= select_tag(:category_id, options_from_collection_for_select(c_array,'id', 'name'), include_blank:"All", style:"height: 30px; text-transform: capitalize;", class: " border_color") %>
<%= submit_tag("Search", style: "font-size:12px;", class: "btn btn-sm btn-outline-secondary ml-2", type: "submit") %>
<% end %>

app/views/products/_shopping_cart.html.erb
<article>
  <% if notice %>
    <aside id="notice"><%= notice %></aside>
  <% end %>
  <h2>Your Cart</h2>
  <table>

      <%= render cart.line_items %>

    <tfoot>
      <tr>
        <th colspan="2">Total:</th>
        <td class="price"> <%= number_to_currency(cart.total_price) %></td>
      </tr>
    </tfoot>
  </table>
  <%= button_to 'Empty cart', cart, method: :delete, data: {confirm: 'Are you sure?'} %>
</article>

app/views/products/index.html.erb
<div class="row">
  <div class="col-sm-4 mt-2">
    <%= render 'shared/categories' %>
  </div>
  <div class="col">
    <%= render 'shared/products' %>
  </div>
</div>

app/views/products/search.html.erb
<h4>
  Found <span style="color:red;"><%= pluralize(@products.count, "product") %></span>
  for the search term <span style="color:red;">"<%= params[:search_term] %> " </span> in  <span style="color:red;">
    <% if @cate != nil %>
      <%= @cate.name %>
    <% else %>
      <%= "All" %>
    <% end %>
  </span>.
</h4>
<div class="row d-flex justify-content-center d-flex flex-row bd-highlight mb-3">
  <% if @products.empty? %>
  <p>There are no products available.</p>
<% else %>
  <% @products.each do |product| %>
       <div class="col">
  <div class="card text-center ml-4 mb-4 p-2 " style="width: 11rem; height: 23rem;">
    <% if product.image.empty? %>
      <p><%= link_to image_tag(product.active_image.variant(resize_to_limit: [150, 200]).processed, alt: "#{product.name}", class: "border rounded"), product if product.active_image.attached? %></p>
    <% else %>
      <p><%= link_to image_tag("#{product.image}", alt: "#{product.name}", style: "width:150px; height:200px;", class: "border rounded"), product %></p>
    <% end %>
    <div class="card-body" style="overflow: hidden; white-space:nowrap; text-overflow:ellipsis;">
      <small class="card-title" ><strong><%= link_to "#{product.name}", product, class: "text-reset" %></strong> </small>
      <br >
      <small class="card-text">Price: <%= number_to_currency product.price %> </small>
    </div>
    <small><%= link_to("Quick Look", product, class: "btn text-success mb-2", style: "font-size: 1em; width: 6rem; height: 2rem;") %></small>
  </div>
</div>
  <% end %>
<% end %>
</div>

app/views/products/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"> <%= link_to "Home", root_path, class: "text-success" %></li>
    <li class="breadcrumb-item active"><%= link_to @cate.name, products_path(@cate.id), class: "text-success" %></li>
    <li class="breadcrumb-item active text-success"><%= @product.name %></li>
  </ol>
</nav>
<div class="row mr-2 ml-2 mt-5 pt-5">
  <div class=" col-lg-4 ">
    <% if @product.image.empty? %>
      <p><%= image_tag(@product.active_image.variant(resize_to_limit: [250, 350]).processed, alt: "#{@product.name}", class: "border rounded") if @product.active_image.attached? %></p>
    <% else %>
      <p><%= image_tag("#{@product.image}", alt: "#{@product.name}", style: "width:250px; height:350px;", class: "border rounded") %></p>
    <% end %>
  </div>
  <div class="col">
    <div class="row">
      <h6>Product Name: <%= @product.name %></h6>
    </div>
    <div class="row">
      <p>Price: <%= number_to_currency @product.price %></p>
    </div>
    <div class="row">
      <p>Category: <%= @cate.name %></p>
    </div>
    <% if @product.is_in_stock %>
      <div class="row">
        <p> Stock: On </p>
      </div>
    <% else %>
      <div class="row">
        <p> Stock: Off </p>
      </div>
    <% end %>
    <div class="row">
      <p>Discount Rate: <%= @product.discount_rate %> %</p>
    </div>
    <div class="row"><small><strong> Description: </strong></small><br >
      <small><%= @product.description %></small></div>
    <br >
    <% if current_devise_user %>
    <p>Quantity: </p>
      <%= form_for @line_item, url: line_items_path(product_id: @product), method: :post do |f| %>
        <%= f.hidden_field :product_id, :value => @product.id %>
        <%= f.number_field :quantity, :vaue => 1, :min => 1, class: "rounded-sm pt-1 pb-1", style: "width:100px;" %>
        <%= f.submit "Add to Cart", class: "btn text-success" %>
      <% end %>
    <% end %>
  </div>
</div>