config/routes.rb
Rails.application.routes.draw do
  # devise_for :devise_users, :controllers => {registrations: "devise_users/registrations"}

  # devise_for :devise_users, :controllers => {registrations: "devise_users/registrations",
  #                                            sessions: "devise_users/sessions"} do
  #       get "devise_users/sign_up", to: "devise_users/registrations#new"
  # end

  devise_for :devise_users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: "products#index"

  # generate all 7 RESTful routes:

  resources :pages

  resources "products", only: %i[index show]
  resources :shopping_carts
  resources :line_items
  resources :addresses

  get "categories", to: "categories#index"

  get "search", to: "products#search", as: "search" #search_path

  get "/p/:permalink", to: "pages#permalink", as: "permalink"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :province
  belongs_to :devise_user
  validates :street_number, :apartment_number, :city, :postcode, :devise_user_id, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/models/devise_user.rb
class DeviseUser < ApplicationRecord
  # before_action :authenticate_user!
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :addresses
  has_one :shopping_cart
  has_one_attached :image
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :shopping_cart
  validates :quantity, :product_id, :shopping_cart_id, presence: true


end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :devise_user
  has_many :order_products
  validates :o_price, numericality: true
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_products
  has_many :line_items
  validates :name, :price, :is_in_stock, :description, :category_id, presence: true
  validates :price, numericality: true
  has_one_attached :active_image
  validates :discount_rate, presence: false
  paginates_per 9

  before_destroy :ensure_not_referenced_by_any_line_item

  private
  #ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, 'Line Items present')
      throw :abort
    end
  end
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :addresses
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :devise_user

  has_many :line_items, dependent: :destroy

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/callback_helper.rb
module CallbackHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_menu.html.erb
 <!-- Begin Bootstrap Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light ">
  <%= image_tag("Ginger_Bear.jpg", :alt => "Ginger_Bear")%> <%= link_to "Ginger Bear", root_path, class: "navbar-brand text-success font-italic font-weight-bold" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <!--search -->
      <li class="nav-item search_form">
        <%= render partial: "products/search_form" %>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto ">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link active text-muted" %><span class="sr-only">(current)</span>
      </li>
      <li class="nav-item">
        <%= link_to "About", permalink_path("about_us"), class: "nav-link text-muted" %>
      </li>
      <li class="nav-item">
        <%= link_to "Contact Us", permalink_path("contact"), class: "nav-link text-muted" %>
      </li>

      <% if devise_user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Cart (#{@all_items_count})", shopping_carts_path, class: "nav-link text-muted " %>
      </li>
      <% end %>
      <% if devise_user_signed_in? %>
        <li class="nav-item">
          <%= link_to("Log out", destroy_devise_user_session_path, method: :delete, class: "nav-link text-muted") %>
        </li>
        <li class="nav-item nav-link text-muted pt-2">
          Hello, <%= current_devise_user.email.split("@").first %>!
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to("Register", new_devise_user_registration_path, class: "nav-link text-muted") %>
        </li>
        <li class="nav-item">
          <%= link_to("Login", new_devise_user_session_path, class: "nav-link text-muted") %>
        </li>
      <% end %>




      <% if devise_user_signed_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          My Account
        </a>
        <div class="dropdown-menu text-muted" aria-labelledby="navbarDropdown">
          <a class="dropdown-item text-muted" href="#">My Order</a>
          <%= link_to("My Address", addresses_path, class: "dropdown-item text-muted") %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item " href="#">Personal Information</a>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</nav>
<!-- End Bootstrap Navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html >
<html lang="en">
  <head>
    <title>Ginger Bear Store</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body>
  <%= render 'layouts/menu' %>
  <% if notice %>
  <div class="list-group-item list-group-item-success text-center">
    <p class="notice"><%= notice %></p>
    </div>
  <% end %>
  <% if alert %>
    <div  class="list-group-item list-group-item-danger text-center">
      <p class="alert"><%= alert %></p>
    </div>
  <% end %>
  <div class="container-md hope_fullpage">
      <%= yield %>
  </div>


<!-- Footer -->
 <footer class="footer ">
    <div class="container text-center font-weight-bold text-muted">
      <p><small>Copywrong films by Thu Mai</small></p>
    </div>
  </footer>
<!-- Footer -->
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :permalink %>
    <%= form.text_field :permalink %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

<p class="certain"></p>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Permalink</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.content %></td>
        <td><%= page.permalink %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/permalink.html.erb
<h2><%= @page.title %></h2>
<article>
  <p><%= @page.content %></p>
  <% if  @page.permalink == 'about_us'%>
      <h4>About Us</h4>
      <p>The digital age with the rise of YouTube, iTunes, Netflix, etc.
      has made the disc obsolete. However, there are still many people who love the CD with many memories.
      And especially when it also gradually becomes a hobby of collection.</p>

      <p>Speaking of which, many people will feel discouraged. In fact, the original CD stores in Winnipeg have not all disappeared.
      And lucky for you to have known us. Because the place that we refer to here is the place to sell original CDs in Winnipeg that you are looking for.
      That is Ginger Bear.</p>

      <p>With the growing trend of e-commerce, you can buy original CD with just one click. You just need to go to the Ginger Bear website, choose your favorite CD or contact them directly.
      If you are tired of listening to music on YouTube, iTunes and want to find memories with familiar CDs, come to Ginger Bear.
      With many years of experience and top reputation, this will be a place to sell original CDs in Winnipeg that make you satisfied.
      Quickly find and buy discs at Ginger Bear to relive the sky of memories.
      </p>
      <div>
      <%= image_tag("Ginger_Bear.PNG", :alt => "Ginger_Bear")%>
      </div>
  <%elsif @page.permalink == 'contact'  %>
      <p>📍: 160 Princess St, Winnipeg, MB R3B 1K9</p>
      <p>⏰: Mon - Sat: 7AM - 9PM, Sun: 9AM - 9PM.</p>
      <p>📱: (431) 336-3457</p>
      <p>🌐: www.gingerbear.com</p>
  <% end %>

</article>
<p>Last updated: <%= @page.updated_at %></p>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @page.content %>
</p>

<p>
  <strong>Permalink:</strong>
  <%= @page.permalink %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/shared/_breadcrumb.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">

      <% if !category.nil? %>
      <li class="breadcrumb-item"> <%= link_to 'Home', root_path, class:"text-success" %></li>
      <li class="breadcrumb-item active"><%= link_to category.name, products_path(category.id), class:"text-success"%></li>
      <% else %>
      <li class="breadcrumb-item"> <%= link_to 'Home', root_path, class:"text-success" %></li>
      <% end %>
  </ol>
</nav>

app/views/shared/_categories.html.erb
<div class="card">
  <div class="card-header">
    Categories
  </div>
  <div class ="card-body">
    <ul class="list-group">
      <% @categories.each do |ca| %>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <h6><%= link_to ca.name, products_path(cate: ca.id), class:"text-reset"%></h6>
          <span class="badge badge-primary badge-success" ><%= ca.products.count %></span>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_products.html.erb
<%= render partial: "shared/breadcrumb", locals:{category: @category } %>
<div class="row mt-2 ">
  <%= paginate @products, window: 2 %>
</div>
<div class="row d-flex justify-content-center d-flex flex-row bd-highlight mb-3 ">
  <% if @products.empty? %>
    <p>There are no products available.</p>
  <% else %>
    <% @products.each do |product|  %>
      <div class="col">
        <div class="card text-center ml-4 mb-4 p-2 " style="width: 11rem; height: 23rem;">
          <% if product.image.empty? %>
            <p><%= link_to image_tag(product.active_image.variant(resize_to_limit: [150, 200]).processed, alt: "#{product.name}", class: "border rounded"), product if product.active_image.attached? %></p>
          <% else %>
            <p><%= link_to image_tag("#{product.image}", alt: "#{product.name}", style:"width:150px; height:200px;", class: "border rounded"), product %></p>
          <% end %>
          <div class="card-body" style="overflow: hidden; white-space:nowrap; text-overflow:ellipsis;">
            <small class="card-title" ><strong><%= link_to "#{product.name}", product,class:"text-reset" %></strong> </small>
            <br >
            <small class="card-text">Price: <%= number_to_currency  product.price %> </small>
          </div>
          <small><%= link_to("Quick Look", product, class:"btn text-success mb-2", style:"font-size: 1em; width: 6rem; height: 2rem;")%></small>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<div class="row mt-4">
  <%= paginate @products,window: 2 %>
</div>